# Generated by Django 4.2.3 on 2023-07-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=25)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='Prof_pic/')),
                ('Address', models.TextField(blank=True, max_length=50, null=True)),
                ('Phone_Number', models.TextField(blank=True, max_length=15, null=True)),
                ('Date_Of_Birth', models.TextField(blank=True, max_length=25, null=True)),
                ('Gender', models.CharField(blank=True, max_length=8, null=True)),
                ('Religion', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
